name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo código fonte
        uses: actions/checkout@v4.2.2
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Construindo imagem Docker
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/aula-primeira-pipeline:v${{github.run_number}}
            ${{ secrets.DOCKERHUB_USERNAME }}/aula-primeira-pipeline:latest
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Heroku Run
        uses: michcio1234/heroku-run@0.1.1
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          command: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/aula-primeira-pipeline:v${{github.run_number}}
            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/aula-primeira-pipeline:v${{github.run_number}} registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
            docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
            heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
                